### ISSUE TITLE
When using allowOverlap prop the onLayoutsChanged event is not fired when dragging of an item ends

### ISSUE THREAD

**Issue by glennholland** [react-grid-layout/react-grid-layout#1606]
Issue: When using allowOverlap prop the onLayoutsChanged event is not fired onDragStop. 

I have made a sandbox showing the issue. Watch the counters above the grid and move the items to see the issue when items are dragged. This is not affecting resizing of items.

- Expected behaviour: 
- Each time and item is dragged: 
-      onDragStop counter increases by 1 ✅
-      onLayoutChanged counter increases by 1 ❌
-      onResizeStop Counter remains the same ✅
-   Each time an item is resized: 
-      onResizeStop counter is increased by 1 ✅
-      onLayoutChanged counter is increased by 1 ✅
-      onDragStop counter remains the same ✅

Example of issue: https://rb7fq.csb.app/
Sandbox of issue: https://codesandbox.io/s/exciting-brahmagupta-rb7fq

**Comment by cynicaloptimist** [comment]
I noticed this issue too. It's also noticeable in the _Allow Overlap_ demo out-of-the-box; note how the layouts display does not update: https://react-grid-layout.github.io/react-grid-layout/examples/19-allow-overlap.html

**Comment by glennholland** [comment]
Just realised this is a duplicate of #1564. 

Leaving open for now just in case the examples and sandbox are of use, but anyone reading this might want to follow the other issue too.

**Comment by woollsta** [comment]
I wonder if when allowOverlap is enabled it doesn't make a copy of the layout as it would when it applies compaction and collision rules, so it ends up directly mutating the layout.

E.g. this line inside the onDrag method:

https://github.com/react-grid-layout/react-grid-layout/blob/a707cf77735c0531d23524059e9e0ea7d4e5ded0/lib/ReactGridLayout.jsx#L307-L312

It looks like the `compact()` method creates a new array, but when we have allowOverlap it just returns the original layout object.

My hunch is that when it comes to this line in the `onLayoutMaybeChanged` method...

https://github.com/react-grid-layout/react-grid-layout/blob/a707cf77735c0531d23524059e9e0ea7d4e5ded0/lib/ReactGridLayout.jsx#L368-L374

oldLayout will already be equal to newLayout, so no `onLayoutChange` is fired.

**Comment by STRML** [comment]
Thanks, this is now fixed.

**Comment by woollsta** [comment]
Hey @STRML , I've given your latest change a go on my local project and I'm still seeing the bug in the following situations:
* when you change position of item that does not collide/overlap with another item, onLayoutChanged does not fire.
* when you move item to overlap another item, onLayoutChanged fires intermittently
* when moving overlapping items around ontop of eachother so that they remain touching, onLayoutChanged does not fire.

Just to make sure my Grid props are correct, here's what I've got it set to:
![image](https://user-images.githubusercontent.com/3171254/143856181-103b6752-caae-4cc8-b2a9-bf82a00cb632.png)

**Comment by STRML** [comment]
@woollsta We haven't done a new release yet so unless you're getting it from git, we wouldn't have the fix yet.

**Comment by woollsta** [comment]
Yep it's using the one from git. Specifically my fork of this repo as I needed to modify the package.json to make it build after being fetched by yarn:

https://github.com/woollsta/react-grid-layout

![image](https://user-images.githubusercontent.com/3171254/143883197-d18da024-5d9c-452e-8908-ce30388a7c85.png)

![image](https://user-images.githubusercontent.com/3171254/143883464-91277907-fba7-405e-82ed-ae7064548d26.png)
