### ISSUE TITLE
The display position of the dragged element is abnormal

### ISSUE THREAD

**Issue by Pzx1997** [react-grid-layout/react-grid-layout#2221]
### Describe the bug

I'm considering whether to use this library. I found this issue when looking at the official demo. Is this correct?

https://github.com/user-attachments/assets/e21bfe85-424f-4dcc-8234-39bea5988ba1

### Your Example Website or App

https://github.com/user-attachments/assets/e21bfe85-424f-4dcc-8234-39bea5988ba1

### Steps to Reproduce the Bug or Issue

All cases on the official website can be reproduced by clicking on the elements.

### Expected behavior

The position of the dragged element should follow the mouse.

### react-grid-layout library version

2.2.0

### Operating System Version

macOS

### Browser

Chrome

**Comment by STRML** [comment]
This is fixed in v2.2.0! The "placeholder appearing on click" behavior was addressed with the new `dragConfig.threshold` option.

In v2, the default threshold is 3px - the drag placeholder only appears after the mouse has moved beyond this threshold:

```jsx
<GridLayout dragConfig={{ threshold: 3 }} ... />
```

Please test with v2.2.0+ where clicking without dragging no longer shows the placeholder.

**Comment by pawojciechowski** [comment]
@STRML it's not fixed - I'm experiencing the same issue. The problem is that when the main app container is relative & positioned not at x: 0, y: 0 (e.g. you have a sidebar), then after the click the drag placeholder is wrongly positioned via transform (it seems the transform is used based on the browser window, not the actual container position). Can reproduce using 2.2.0 with threshold 3 & 10.

**Comment by pawojciechowski** [comment]
The problem is with this fragment:

https://github.com/react-grid-layout/react-grid-layout/blob/9ab22eaf3e8c9faf62113cfcb0cae327ecf6d8ca/src/react/components/GridItem.tsx#L381-L388

& the default strategy:

https://github.com/react-grid-layout/react-grid-layout/blob/9ab22eaf3e8c9faf62113cfcb0cae327ecf6d8ca/src/core/position.ts#L275-L286

It does not adjust for parent at all.

**Comment by pawojciechowski** [comment]
Thanks for the fix!

**Comment by STRML** [comment]
Fixed, releasing 2.2.1 now
